### ISSUE TITLE
Is there any way to use wildcard or regex inside template string?

### ISSUE THREAD

**Issue by vladrose** [kairome/eslint-plugin-grouped-import#1]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/24589019/163361751-1506dd81-6024-4da2-92d5-4c4a4a98e93f.png">

Expected behavior: 
<img width="462" alt="image" src="https://user-images.githubusercontent.com/24589019/163361916-6e6cb48d-2d2e-4b31-a5e4-967d420c231d.png">

**Comment by kairome** [comment]
No, it simply checks that the import path is in your config. In your example it should work if you change it to `path: './assets'`

However, there is logic for specificity as well

That's the config
```js
    'utils': [{ path: 'utils' }],
    'validations': [{ path: 'utils/validations' }],
```

And that's valid import groups
```js
// utils
import u from 'utils/functions';

// validations
import { validateEmpty } from 'utils/validations';
```
